
default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
 
  pool: 5

development:
  <<: *default
  database: rails_belt_exam_development

test:
  <<: *default
  database: rails_belt_exam_test


production:
  <<: *default
  database: rails_belt_exam_production
 
